check-black-format:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0   

    - name: Get changed py-files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
      with:
        files: |
          containers/*/.py
          dags/*/.py
          ml_pipeline/*/.py

    - name: Install black
      run: |
        pip3 install black==22.8.0

    - name: Check format
      run: |
        if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            echo "No py-files in the commit"
        else                    
            echo "Py-files in the commit"
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                # Skip non-Python files
                if [[ "$file" == *.py ]]; then
                    black --check --diff --line-length=79 "$file" || exit 1
                fi
            done    
        fi
